import 'shared/styles/reset.css';
import 'shared/styles/globals.css';
import { Inter } from 'next/font/google';
import { Header } from 'shared/ui/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ru" className="dark-theme">
			<body className={inter.className}>
				<Header />
				{children}
			</body>
		</html>
	);
}
